# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log_indexed.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import log_pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11log_indexed.proto\x12\x14protobuf.log.indexed\x1a\tlog.proto\"\xe8\x01\n\x0fIndexedLogEntry\x12\r\n\x05\x63hunk\x18\x01 \x01(\r\x12\x0e\n\x06offset\x18\x02 \x01(\r\x12\x11\n\ttimestamp\x18\x03 \x01(\x04\x12%\n\x05level\x18\x04 \x01(\x0e\x32\x16.protobuf.log.LogLevel\x12#\n\x04type\x18\x05 \x01(\x0e\x32\x15.protobuf.log.LogType\x12$\n\x03src\x18\x06 \x01(\x0e\x32\x17.protobuf.log.LogSource\x12\x11\n\tsubsystem\x18\x07 \x01(\t\x12\x10\n\x08typeinfo\x18\x08 \x01(\t\x12\x0c\n\x04size\x18\t \x01(\r\"`\n\x05\x43hunk\x12\n\n\x02id\x18\x01 \x01(\r\x12-\n\x04type\x18\x02 \x01(\x0e\x32\x1f.protobuf.log.indexed.ChunkType\x12\x0e\n\x06offset\x18\x03 \x01(\x04\x12\x0c\n\x04size\x18\x04 \x01(\x04\"\x81\x01\n\tIndexData\x12\x0f\n\x07version\x18\x01 \x01(\r\x12+\n\x06\x63hunks\x18\x02 \x03(\x0b\x32\x1b.protobuf.log.indexed.Chunk\x12\x36\n\x07\x65ntries\x18\x03 \x03(\x0b\x32%.protobuf.log.indexed.IndexedLogEntry* \n\tChunkType\x12\t\n\x05PLAIN\x10\x00\x12\x08\n\x04ZSTD\x10\x01\x42T\n@de.htwk_leipzig.naocontrol.backend.internal.protobuf.log.indexedB\x10LogIndexedProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'log_indexed_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n@de.htwk_leipzig.naocontrol.backend.internal.protobuf.log.indexedB\020LogIndexedProtos'
  _globals['_CHUNKTYPE']._serialized_start=519
  _globals['_CHUNKTYPE']._serialized_end=551
  _globals['_INDEXEDLOGENTRY']._serialized_start=55
  _globals['_INDEXEDLOGENTRY']._serialized_end=287
  _globals['_CHUNK']._serialized_start=289
  _globals['_CHUNK']._serialized_end=385
  _globals['_INDEXDATA']._serialized_start=388
  _globals['_INDEXDATA']._serialized_end=517
# @@protoc_insertion_point(module_scope)
